/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanosBpoRouteImport } from './routes/planos.bpo'
import { Route as PlanosControladoriaRouteImport } from './routes/planos.controladoria'
import { Route as PlanosContabilidadeRouteImport } from './routes/planos.contabilidade'

const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosBpoRoute = PlanosBpoRouteImport.update({
  id: '/planos/bpo',
  path: '/planos/bpo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosControladoriaRoute = PlanosControladoriaRouteImport.update({
  id: '/planos/controladoria',
  path: '/planos/controladoria',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosContabilidadeRoute = PlanosContabilidadeRouteImport.update({
  id: '/planos/contabilidade',
  path: '/planos/contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/planos/bpo': typeof PlanosBpoRoute
  '/planos/controladoria': typeof PlanosControladoriaRoute
  '/planos/contabilidade': typeof PlanosContabilidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/planos/bpo': typeof PlanosBpoRoute
  '/planos/controladoria': typeof PlanosControladoriaRoute
  '/planos/contabilidade': typeof PlanosContabilidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/planos/bpo': typeof PlanosBpoRoute
  '/planos/controladoria': typeof PlanosControladoriaRoute
  '/planos/contabilidade': typeof PlanosContabilidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/planos' | '/planos/bpo' | '/planos/controladoria' | '/planos/contabilidade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/planos' | '/planos/bpo' | '/planos/controladoria' | '/planos/contabilidade'
  id: '__root__' | '/' | '/planos' | '/planos/bpo' | '/planos/controladoria' | '/planos/contabilidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanosRoute: typeof PlanosRoute
  PlanosBpoRoute: typeof PlanosBpoRoute
  PlanosControladoriaRoute: typeof PlanosControladoriaRoute
  PlanosContabilidadeRoute: typeof PlanosContabilidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/bpo': {
      id: '/planos/bpo'
      path: '/planos/bpo'
      fullPath: '/planos/bpo'
      preLoaderRoute: typeof PlanosBpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/controladoria': {
      id: '/planos/controladoria'
      path: '/planos/controladoria'
      fullPath: '/planos/controladoria'
      preLoaderRoute: typeof PlanosControladoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos/contabilidade': {
      id: '/planos/contabilidade'
      path: '/planos/contabilidade'
      fullPath: '/planos/contabilidade'
      preLoaderRoute: typeof PlanosContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanosRoute: PlanosRoute,
  PlanosBpoRoute: PlanosBpoRoute,
  PlanosControladoriaRoute: PlanosControladoriaRoute,
  PlanosContabilidadeRoute: PlanosContabilidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
