/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanosControladoriaRouteImport } from './routes/planos_.controladoria'
import { Route as PlanosContabilidadeRouteImport } from './routes/planos_.contabilidade'
import { Route as PlanosBpoRouteImport } from './routes/planos_.bpo'

const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosControladoriaRoute = PlanosControladoriaRouteImport.update({
  id: '/planos_/controladoria',
  path: '/planos/controladoria',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosContabilidadeRoute = PlanosContabilidadeRouteImport.update({
  id: '/planos_/contabilidade',
  path: '/planos/contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosBpoRoute = PlanosBpoRouteImport.update({
  id: '/planos_/bpo',
  path: '/planos/bpo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/planos/bpo': typeof PlanosBpoRoute
  '/planos/contabilidade': typeof PlanosContabilidadeRoute
  '/planos/controladoria': typeof PlanosControladoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/planos/bpo': typeof PlanosBpoRoute
  '/planos/contabilidade': typeof PlanosContabilidadeRoute
  '/planos/controladoria': typeof PlanosControladoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planos': typeof PlanosRoute
  '/planos_/bpo': typeof PlanosBpoRoute
  '/planos_/contabilidade': typeof PlanosContabilidadeRoute
  '/planos_/controladoria': typeof PlanosControladoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/planos'
    | '/planos/bpo'
    | '/planos/contabilidade'
    | '/planos/controladoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/planos'
    | '/planos/bpo'
    | '/planos/contabilidade'
    | '/planos/controladoria'
  id:
    | '__root__'
    | '/'
    | '/planos'
    | '/planos_/bpo'
    | '/planos_/contabilidade'
    | '/planos_/controladoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanosRoute: typeof PlanosRoute
  PlanosBpoRoute: typeof PlanosBpoRoute
  PlanosContabilidadeRoute: typeof PlanosContabilidadeRoute
  PlanosControladoriaRoute: typeof PlanosControladoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos_/controladoria': {
      id: '/planos_/controladoria'
      path: '/planos/controladoria'
      fullPath: '/planos/controladoria'
      preLoaderRoute: typeof PlanosControladoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos_/contabilidade': {
      id: '/planos_/contabilidade'
      path: '/planos/contabilidade'
      fullPath: '/planos/contabilidade'
      preLoaderRoute: typeof PlanosContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos_/bpo': {
      id: '/planos_/bpo'
      path: '/planos/bpo'
      fullPath: '/planos/bpo'
      preLoaderRoute: typeof PlanosBpoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanosRoute: PlanosRoute,
  PlanosBpoRoute: PlanosBpoRoute,
  PlanosContabilidadeRoute: PlanosContabilidadeRoute,
  PlanosControladoriaRoute: PlanosControladoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
